// Generated by CoffeeScript 1.10.0
(function() {
  var article, header, parallax;

  header = document.getElementsByTagName("header")[0];

  parallax = document.getElementsByClassName("parallax")[0];

  article = document.getElementsByTagName("article")[0];

  window.addEventListener('scroll', function() {
    var scrolltop;
    scrolltop = window.pageYOffset;
    header.style.opacity = 1 - scrolltop * .02;
    parallax.style.opacity = 1 - scrolltop * .003;
    return parallax.style.top = -scrolltop * .32 + 40 + 'px';
  });

}).call(this);
